CC=gcc
CFLAGS=-Wall -g

all: hw51 hw52 hw53

hw51: hw51.c
	$(CC) $(CFLAGS) hw51.c -o hw51

hw52: hw52.c
	$(CC) $(CFLAGS) hw52.c -o hw52

hw53: hw53.c
	$(CC) $(CFLAGS) hw53.c -o hw53

clean:
	rm -rf hw51 hw52 hw53

